### ISSUE TITLE
Upquark quantumfieldblock

### ISSUE THREAD

**Issue by MajaVerstraeten** [ElementaryMinecraft/ElementaryCraft#1]
Zie google document 'Kwantumveldblokken'

Bij minen (of rechterklik indien nodig) spuwt de blok tegelijkertijd een upquark en anti-upquark, met 1/3 kans op rood groen of blauw. De kwantumveldblok blijft bestaan!

Bij minen met silk touch, krijgt men quantumfieldblock.

**Comment by MHoutput** [comment]
Dit is geïmplementeerd en (hopelijk) gesynched naar de branch "upquarkmh".

Zaken om te bespreken:
- Snelheid van het minen van een kwantumveldblok (hardness)
- Kan je door het kwantumveldblok wandelen (aangezien het "kwantumveld" niet materiëel is)?
- De implementatie gebeurt via een procedure, is dit 100% foolproof?
- Spawning properties van de kwantumveldblokken

Nog te implementeren:
- Betere afbeeldingen voor de quarks en voor het kwantumveldblok
