### ISSUE TITLE
Photon farm

### ISSUE THREAD

**Issue by MajaVerstraeten** [ElementaryMinecraft/ElementaryCraft#17]
Als naast een fotonveldblok, met een tussenruimte van één blok, een materiedeeltje met een elektrische lading geplaatst worden (zoals een elektron), dan geeft het fotonveldblok spontaan fotonen aan dat materiedeeltje. Het materiedeeltje geeft die fotonen echter ook terug aan het fotonveldblok. Af en toe valt er een foton-item uit. De speler kan hier een hopper bij plaatsen zodat de fotonen worden opgevangen.

**Comment by BertJorissen** [comment]
De animaties van textures kan hierbij wel toegepast worden. Ik zal dit zo snel mogelijk implementeren.
De ewtra tussenruimte zorgt voor een iets moeilijkere implementatie dan deze van de annihilatie, maar dit is zeker nog doenbaar.
