### ISSUE TITLE
Gluon (en quark) farm

### ISSUE THREAD

**Issue by MajaVerstraeten** [ElementaryMinecraft/ElementaryCraft#18]
Als gluon-farm kan je quarks (en anti-quarks) uiteen trekken.

Men kan een pion craften. Het pionen wordt tussen twee mining carts geplaatst. Die carts rijden van elkaar weg en trekken zo de quark en anti-quark van het pion uiteen.
Aan het uiterlijk van het pion item moet te zien zijn dat het bestaat uit quark-gluon-antiquark.
De carts rijden uit elkaar.
Wanneer de carts twee blokken van elkaar verwijderd zijn, verandert het pion en quark (blok 1) en antiquark (blok2).
Wanneer de carts drie blokken van elkaar verwijderd zijn, komt er een gluon tussen de quark en het antiquark.
Wanneer de carts nog meer blokken van elkaar verwijderd zijn, komen er steeds meer gluonen tussen de quark en het antiquark.
Wanneer pakweg 10 gluonen gevormd zijn, en de carts rijden nog verder uit elkaar, dan komen er een quark en een antiquark bij, zodat men twee ketens heeft van quark-gluon-...-gluon-antiquark.
Er moet een gluonveldblok in de buurt staan zodat duidelijk wordt dat de nieuwe gluonen uit het gluonveld komen. Gemakkelijk is om de gluonveldblok in de minecart te zetten.

**Comment by MajaVerstraeten** [comment]
Tom schreef bij de pull request van de gluon farm het volgende:

First implementation of the gluon farm.

Setup:

Place down two powered rails with a one block gap in between, extend the track with normal rails to either side. Next, place two minecarts, one on each of the powered rails. Finally place a pion block in between the minecarts, place a button on the pion block and press the button.

Two remarks:

I've had to set the pion to be non-transparent, due to the way the farm works. Hopefully we can find a way around this with the textures.
    Currently the pion does not really get destroyed, I'm just relying on the decay feature. This can be changed, I'm just not 100% sure what had to happen.

Lastly I've also had to resort to custom coding this procedure, since mcreator was too limiting. The main thing that might want to be changed is the "TICKS" variable (near the top of the class), it determines how often gluons will spawn when the minecarts are moving. The lower the value, the more often they will spawn.

**Comment by MajaVerstraeten** [comment]
Tom mentioned in his pull request:
Currently the pion does not really get destroyed, I'm just relying on the decay feature. This can be changed, I'm just not 100% sure what had to happen.

This confusion can be caused by the typo in the sentence below:
 Wanneer de carts twee blokken van elkaar verwijderd zijn, verandert het pion en quark (blok 1) en antiquark (blok2).

It should say,
verandert het pion IN EEN quark (blok1) en antiquark (blok2).

So from the moment that the carts start driving apart, the pion disappears and in stead a quark and an antiquark appear. Ideally they would stick at the back of the cart. 
| cart | pion | cart |
| cart | quark | antiquark | cart |
| cart | quark | gluon | antiquark | cart |
| cart | quark | gluon | gluon | antiquark | cart |
| cart | quark | gluon | ... gluons ... | gluon | antiquark | cart |

in the above, the gluons are always floating above the ground as items that you can pick up
The quarks are currently implemented as pure items. They should stick at the back of the cart (possible?) or they should be inside the cart (if that's easier).  I can imagine for the former, you would have to make a dedicated texture 'cart with quark attached'

In the final stage, the quarks should be recombined into pions. 
| cart | pion | gluon | ... gluons ... | gluon | pion | cart |
where the pions are real blocks and the gluons are floating items.

**Comment by BertJorissen** [comment]
Een volledige implementatie, mét animaties, heeft een nieuwe implementatie van entities nodig. Dit maakt het moeilijker om goed te implementeren. Als Tom eventueel weet hoe een animatie te maken met entities, kan het label 'moeilijk' weggehaald worden.

**Comment by BertJorissen** [comment]
Ik denk dat een uitrbeiding van het script van Tom mogelijks een betere fysische interpretatie mogelijk maakt. Er worden één of twee costum blocks gemaakt die de up/down quarks voorstellen door over de gewone grenzen van een blok te tekenen, zodat het blok in essentie uit de minecart hangt, hierbij kunnen we bijvoorbeeld tonen dat de quarks uit elkaar getrokken worden. De minecarts worden getriggerd door de Neighbourhood call van de pionen te gebruiken, waarbij gekeken wordt naar minecarts in de omgeving. De minecarts worden weggehaald, en vervangen door andere minecarts met het 'summon' commando uit de minecraft 'console'. De rest van het script verloopt analoog, maar als de snelheid van teken verandert of een component heeft in een andere richting, 'breekt' de pionketting en valt de minecart stil. Door de minecart een kleine beginsnelheid te geven, kan met een powered rail wél de beweging automatisch gemaakt worden. Als de minecart stil valt, wordt deze vervangen door een nieuwe minecart zonder een pion aan vast. Ik denk dat deze implementatie wel doenbaar is om te maken, ik zal dit proberen dit weekend te onderzoeken. Ook laat deze implementatie toe het process te automatiseren met bvb dispensers, zodat je de gluonen kunt opvangen onder de rails.

**Comment by BertJorissen** [comment]
De eerste versie is nu af, maar de textures moeten nog veranderd worden. Ook zijn er nog enkele kleine foutjes die er misschien nog uit moeten, maar op zich is het vrij stabiel. 
![ezgif-3-bfb3a497d4e4](https://user-images.githubusercontent.com/61983794/99919675-1dac4f80-2d1f-11eb-8848-8836ae544866.gif)
