### ISSUE TITLE
Downquark quantumfield block

### ISSUE THREAD

**Issue by MajaVerstraeten** [ElementaryMinecraft/ElementaryCraft#2]
Zie google document 'Kwantumveldblokken'

Bij minen (of rechterklik indien nodig) spuwt de blok tegelijkertijd een downquark en anti-downquark, met 1/3 kans op rood groen of blauw. De kwantumveldblok blijft bestaan!

Bij minen met silk touch, krijgt men downquark quantumfieldblock.

**Comment by MHoutput** [comment]
De down quarks zijn geïmplementeerd op dezelfde manier als de up-quarks. Ze staan ook op dezelfde branch (upquarksmh).

Zie de comment bij de issue "Upquark quantumfield block" voor alle verdere informatie over de implementatie.
