### ISSUE TITLE
Coulomb force

### ISSUE THREAD

**Issue by MajaVerstraeten** [ElementaryMinecraft/ElementaryCraft#30]
Dit is een interessante eigenschap voor stabiele deeltjes (allemaal items) met een elektrische lading die men in de wereld kan plaatsen:

Elektron -1
Proton +1
Pion +1
Pion -1

Het feit dat alle deeltjes een lading van 1 hebben, maakt dit al een stuk gemakkelijker.Als men deeltjes-items met een elektrische lading met hetzelfde teken naast elkaar zet, dan verschuiven die automatisch elks een blok opzij zodat er een afstand van twee blokken tussen de deeltjes komt.De spelers kunnen deze eigenschap gebruiken naar believen. Zoals bijvoorbeeld om een zwevend gebouw te bouwen en om dat gebouw te verplaatsen.

Qua implementatie kan dit analoog gedaan worden aan een piston in vanilla minecraft? Zo kunnen pistons maximaal 12 andere blokken verschuiven, zijn sommige blokken onmogelijk te verschuiven (zoals obsidian) en worden andere blokken vernietigd wanneer je ze probeert te verschuiven.

**Comment by BertJorissen** [comment]
Ik heb de implementatie niet gedaan als een _piston_, maar de meeste funcitonaliteit van verschuivingen etc. is wel aanwezig. Als we dit echt als een _kracht_ willen aanzien, stel ik voor om dit te behandelen in een ander issue. Mogelijks kan er dan een voorwaarde worden opgelegd van een massa en een groote van de coulombkracht om het bovenliggende of blok ernaast te kunnen verschuiven. Hierbij is zeer belangrijk om af te vragen welk blok er verschuift (derde wet van Newton), wat een piston wordt die langs beide richtingen werkt(?!).
