### ISSUE TITLE
Spontaneous weak decay

### ISSUE THREAD

**Issue by MajaVerstraeten** [ElementaryMinecraft/ElementaryCraft#32]
Enkele elementaire deeltjes zijn onstabiel.

Een neutron heeft een iets grotere massa dan het proton dus het neutron zal na verloop van tijd spontaan vervallen (veranderen) in een proton.
Als een neutron item in de minecraft wereld geplaatst wordt, dan verandert het na enkele ticks in een proton en spawnt een W boson. 

Ook pionen vervallen in een fractie van een seconde. De vervalkanalen van de pionen zijn iets ingewikkelder maar als we stoppen bij het W boson vermijden we die complexiteit. Bijvoorbeeld, de geladen pionen vallen bijna altijd uiteen in een (anti-)muon en een (anti-)muon-neutrino, via een W boson.
In minecraft, wanneer een GELADEN pion (+ of -) in de wereld wordt geplaatst, dan verandert het pion simpelweg in een zwevend W boson. 
De neutrale pionen vallen bijna altijd uiteen in twee fotonen. Dus als een speler een neutraal pion in de wereld plaatst verandert dat in twee (zwevende) fotonen.

**Comment by DietrichElst** [comment]
Hoe wil je juist een neutron **item** in de wereld plaatsen?

**Comment by MajaVerstraeten** [comment]
Antwoord for future reference: Enkele items zijn achter de schermen blokken geworden zodat zij in de wereld geplaatst kunnen worden. Voor de speler gaan ze nog steeds overkomen als items. (cfr torch)

**Comment by MajaVerstraeten** [comment]
Eigenlijk vervallen de geladen pionen via W naar muon en antimuonneutrino. Wij hebben in elementary craft die deeltjes echter niet. Wanneer het W boson in de wereld wordt geplaatst dan vervalt het in eCraft steeds naar electron en anti electron neutrino. Dit is ook een toegestaan vervalkanaal voor de geladen pionen al komt deze minder vaak voor:

the primary decay mode of a Pion, with probability 0.999877, is a purely Leptonic decay into an anti-Muon and a Muon Neutrino.
The second most common decay mode of a Pion, with probability 0.000123, is also a Leptonic decay into an Electron and the corresponding Electron anti-Neutrino. This "electronic mode" was discovered at CERN in 1958.

**Comment by MajaVerstraeten** [comment]
Minecraft's game loop runs at a fixed rate of 20 ticks per second, so one tick happens every 0.05 seconds. An in-game day lasts exactly 24000 ticks, or 20 minutes.

A free neutron is unstable, decaying to a proton, electron and antineutrino with a mean lifetime of just under 15 minutes (881.5±1.5 s). 

Suppose N is the size of a population of radioactive atoms at a given time t, and dN is the amount by which the population decreases in time dt; then the rate of change is given by the equation dN/dt = −λN, where λ is the decay constant. 
The time required for half of the original population of radioactive atoms to decay is called the half-life.
The relationship between the half-life, T1/2, and the decay constant is given by T1/2 = 0.693/λ.

1 minecraft-dag = 24000 ticks = 20 echte minuten
1 MC-uur           = 1000 ticks    = 50 echte seconden
15 MC-minuten = 250 ticks       = 12,5 echte seconden

Kans op verval bij iedere tick zodat na 250 ticks 1/2 overblijft? 
1 - (1/2)^1/250 = 0.0027687486479305138489752220812614800738700952763635850913047346



Mean lifetime Pionen
π±: 2.6×10−8 s, 
Kans op verval bij iedere tick zodat na 30 ticks 1/2 overblijft?
1 - (1/2)^1/30 =  0.0228400315657540450673018538223454763336870612521282099649243251

π0: 8.4×10−17 s
Kans op verval bij iedere tick zodat na 20 ticks 1/2 overblijft? 
1 - (1/2)^1/20 = 0.0340636710751544489348556870795361006092626871207474193331061394

Mean half-life w boson about 3×10−25 s. 
Kans op verval bij iedere tick zodat na 10 ticks 1/2 overblijft? 
1 - (1/2)^1/10 = 0.0669670084631925840186567338500578329727700356485059610995026145
