### ISSUE TITLE
particle anti-particle annihilation

### ISSUE THREAD

**Issue by MajaVerstraeten** [ElementaryMinecraft/ElementaryCraft#33]
Wanneer een deeltje en het overeenkomstig antideeltje elkaar raken in de wereld (met een vlak) dan verdwijnen de blokken, er is een lichtflits en er worden twee fotonen uitgespuwd

**Comment by MajaVerstraeten** [comment]
Dit geldt voor  elektron - postiron en voor een neutrino - antineutrino 
Dit geldt niet voor quark - antiquark want deze kan men toch niet in de wereld plaatsen. Een pion die bestaat uit quark en anti-quark gaat wel annihileren en bijgevolg verdwijnen en twee fotonen spawnen.

Er is geen lichtflits zichtbaar bij de annihilatie

**Comment by BertJorissen** [comment]
De implementatie werkt niet goed met de Coulombkracht. Deze implementatie zal ik dus bekijken en mogelijks aanpassen.
![ezgif-6-bd89e8ca67ef](https://user-images.githubusercontent.com/61983794/95359579-9fa8fc00-08ca-11eb-92a6-a3305c60dda4.gif)
