### ISSUE TITLE
Entropie-mob

### ISSUE THREAD

**Issue by BertJorissen** [ElementaryMinecraft/ElementaryCraft#59]
Creeper->entropy

**Comment by MajaVerstraeten** [comment]
Zou de entropymob best aangepast worden naar een entropyman? In navolging van de enderman.
Bijvoorbeeld een zombie of villager nemen en die als texture volledig zwart maken met paarse ogen?

Tijdens de vergadering was er geen duidelijke voorkeur voor texture of gedrag
Bert vond het wel leuk dat de entropymob op een creeper lijkt en 'ontploft'

Ine wees erop dat we moeten checken of de speler suffocate wanneer er blokken geplaatst worden
Ik heb de mob enkel uitgeprobeerd in creative mode
We kunenn een loop invoegen zodat er geen blokken worden geplaatst wanneer er een speler op die positie staat  >> DIT IS OPGELOST
