### ISSUE TITLE
weak gaugeboson quantumfieldblock

### ISSUE THREAD

**Issue by MajaVerstraeten** [ElementaryMinecraft/ElementaryCraft#7]
Zie google doc 'kwantumveldblokken'

bij minen (of rechtermuisklik) krijgt men weak gaugeboson. De blok blijft bestaan!

Bij minen met silk touch, maakt men de quantumfieldblock kapot en krijgt deze.

**Comment by DietrichElst** [comment]
Toegevoegd in 'weakgauge' branch met tijdelijke texture
