### ISSUE TITLE
Quark items

### ISSUE THREAD

**Issue by MajaVerstraeten** [ElementaryMinecraft/ElementaryCraft#8]
Zie google document 'quarks'

Een quark kan niet afzonderlijk in wereld geplaatst worden.

upquark (red) item
anti upquark (red) item [ziet er cyaan uit]
downquark (red) item
anti downquark (red) item [ziet er cyaan uit]

upquark (green) item
anti upquark (green) item [ziet er magenta uit]
downquark (green) item
anti downquark (green) item [ziet er magenta uit]

upquark (blue) item
anti upquark (blue) item [ziet er geel uit]
downquark (blue) item
anti downquark (blue) item [ziet er geel uit]

**Comment by MHoutput** [comment]
De implementatie gebeurde gelijktijdig met de implementatie van de upquark- en downquark- kwantumveldblokken: deze items zijn te vinden op de branch "upquarksmh". Zie de comment bij de issue "Upquark quantumfield block" voor meer informatie.
